import json
import re
import sys
from pathlib import Path


# ============================================================
# PAN CARD EXTRACTOR
# ============================================================
#
# Extracts ONLY:
#
#   PAN Number
#   Name
#   Father's Name
#   Date of Birth
#
# Input:
#   OCR result JSON generated by Module 3
#
# Output:
#   pan_extracted_data.json
#
# ============================================================


# ============================================================
# HELPERS
# ============================================================

def clean(value):

    if value is None:
        return None

    value = str(value)

    value = re.sub(
        r"\s+",
        " ",
        value
    )

    return value.strip()


def normalize(value):

    value = clean(value)

    if not value:
        return ""

    return value.upper()


def get_lines(ocr_result):

    lines = []

    for item in ocr_result.get(
        "text",
        []
    ):

        if not isinstance(
            item,
            dict
        ):
            continue

        text = clean(
            item.get("text")
        )

        if not text:
            continue

        lines.append({
            "text": text,
            "page": item.get(
                "page_number"
            ),
            "confidence": item.get(
                "confidence"
            ),
            "box": item.get(
                "box"
            )
        })

    return lines


# ============================================================
# PAN NUMBER
# ============================================================

def extract_pan_number(text):

    """
    PAN format:

        AAAAA9999A

    Five letters
    Four digits
    One letter
    """

    if not text:
        return None

    # --------------------------------------------------------
    # Remove spaces and common OCR separators
    # --------------------------------------------------------

    cleaned = re.sub(
        r"[\s\-_/]",
        "",
        text.upper()
    )

    # --------------------------------------------------------
    # Standard PAN pattern
    # --------------------------------------------------------

    matches = re.findall(
        r"(?<![A-Z0-9])"
        r"[A-Z]{5}[0-9]{4}[A-Z]"
        r"(?![A-Z0-9])",
        cleaned
    )

    if matches:

        return matches[0]

    # --------------------------------------------------------
    # Fallback:
    #
    # OCR sometimes places surrounding text directly next
    # to the PAN number.
    # --------------------------------------------------------

    match = re.search(
        r"[A-Z]{5}[0-9]{4}[A-Z]",
        cleaned
    )

    if match:

        return match.group(0)

    return None


# ============================================================
# DATE OF BIRTH
# ============================================================

def extract_dob(text):

    if not text:
        return None

    pattern = (
        r"(?<!\d)"
        r"(\d{1,2})"
        r"\s*[\/\-.]\s*"
        r"(\d{1,2})"
        r"\s*[\/\-.]\s*"
        r"(\d{4})"
        r"(?!\d)"
    )

    matches = re.finditer(
        pattern,
        text
    )

    for match in matches:

        day = int(
            match.group(1)
        )

        month = int(
            match.group(2)
        )

        year = int(
            match.group(3)
        )

        if not (
            1 <= day <= 31
        ):
            continue

        if not (
            1 <= month <= 12
        ):
            continue

        if not (
            1900 <= year <= 2100
        ):
            continue

        return (
            f"{day:02d}/"
            f"{month:02d}/"
            f"{year:04d}"
        )

    return None


# ============================================================
# NAME VALIDATION
# ============================================================

def is_person_name(value):

    if not value:
        return False

    value = clean(value)

    if len(value) < 3:
        return False

    if len(value) > 80:
        return False

    if not re.fullmatch(
        r"[A-Za-z][A-Za-z .'\-]*",
        value
    ):
        return False

    upper = normalize(
        value
    )

    forbidden = [

        "INCOME TAX",

        "DEPARTMENT",

        "GOVT",

        "GOVERNMENT",

        "INDIA",

        "PERMANENT",

        "ACCOUNT",

        "NUMBER",

        "CARD",

        "SIGNATURE",

        "DATE",

        "BIRTH",

        "NAME",

        "FATHER",

        "PAN",

    ]

    for word in forbidden:

        if word in upper:

            return False

    return True


# ============================================================
# NAME
# ============================================================

def extract_name(lines):

    # --------------------------------------------------------
    # Explicit Name label
    # --------------------------------------------------------

    for index, item in enumerate(
        lines
    ):

        line = item["text"]

        upper = normalize(
            line
        )

     

        match = re.search(
            r"(?:^|[\s/])NAME\s*[:\-]\s*(.+)$",
            line,
            flags=re.I
        )

        if match:

            candidate = clean(
                match.group(1)
            )

            if is_person_name(
                candidate
            ):

                return candidate

        # ----------------------------------------------------
       
        # In this particular OCR the name is BEFORE /Name.
        # ----------------------------------------------------

        if (
            "NAME" in upper
            and
            not "FATHER" in upper
        ):

            # Previous OCR line
            if index > 0:

                candidate = clean(
                    lines[index - 1]["text"]
                )

                if is_person_name(
                    candidate
                ):

                    return candidate

            # Next OCR line
            if index + 1 < len(lines):

                candidate = clean(
                    lines[index + 1]["text"]
                )

                if is_person_name(
                    candidate
                ):  

                    return candidate

    return None


# ============================================================
# FATHER'S NAME
# ============================================================

def extract_father_name(lines):



    for item in lines:

        line = item["text"]

        match = re.search(
            r"FATHER(?:'S)?\s*NAME\s*[:\-]\s*(.+)",
            line,
            flags=re.I
        )

        if match:

            candidate = clean(
                match.group(1)
            )

            if is_person_name(candidate):

                return candidate

    

    father_label = None

    for item in lines:

        upper = normalize(
            item["text"]
        )

        if "FATHER" in upper:

            father_label = item

            break

    if father_label:

        label_box = father_label.get(
            "box"
        )

        if label_box:

            label_x = min(
                point[0]
                for point in label_box
            )

            label_y = min(
                point[1]
                for point in label_box
            )

            # ------------------------------------------------
            # Find valid names.
            #
            # The supplied PAN OCR is rotated, therefore
            # horizontal/vertical distance must be treated
            # carefully.
            # ------------------------------------------------

            candidates = []

            for item in lines:

                if item is father_label:
                    continue

                candidate = clean(
                    item["text"]
                )

                if not is_person_name(
                    candidate
                ):
                    continue

                box = item.get(
                    "box"
                )

                if not box:
                    continue

                candidate_x = min(
                    point[0]
                    for point in box
                )

                candidate_y = min(
                    point[1]
                    for point in box
                )

                distance = (
                    abs(candidate_x - label_x)
                    +
                    abs(candidate_y - label_y)
                )

                candidates.append(
                    {
                        "name": candidate,
                        "distance": distance,
                        "x": candidate_x,
                        "y": candidate_y,
                    }
                )

            # ------------------------------------------------
            # IMPORTANT:
            #
            # In this PAN layout the father's name appears
            # BEFORE the student's name in OCR order.
            #
            # If we have two person names, choose the one
            # that is not the extracted cardholder name.
            # ------------------------------------------------

            extracted_name = extract_name(
                lines
            )

            if extracted_name:

                different_candidates = [
                    item
                    for item in candidates
                    if normalize(
                        item["name"]
                    ) != normalize(
                        extracted_name
                    )
                ]

                if different_candidates:

                    different_candidates.sort(
                        key=lambda item:
                            item["distance"]
                    )

                    return different_candidates[0][
                        "name"
                    ]

            # ------------------------------------------------
            # Fallback
            # ------------------------------------------------

            if candidates:

                candidates.sort(
                    key=lambda item:
                        item["distance"]
                )

                return candidates[0]["name"]

    # --------------------------------------------------------
    # 3. Final fallback: look for a name before /Name
    # --------------------------------------------------------

    for index, item in enumerate(
        lines
    ):

        if "NAME" not in normalize(
            item["text"]
        ):

            continue

        for previous_index in range(
            index - 1,
            max(-1, index - 5),
            -1
        ):

            candidate = clean(
                lines[previous_index]["text"]
            )

            if is_person_name(
                candidate
            ):

                return candidate

    return None

# ============================================================
# SIGNALS
# ============================================================

def get_signals(text):

    upper = normalize(
        text
    )

    signals = []

    if (
        "INCOME TAX DEPARTMENT" in upper
        or
        "INCOMETAXDEPARTMENT" in upper
    ):

        signals.append(
            "INCOME_TAX_DEPARTMENT"
        )

    if (
        "PERMANENT ACCOUNT NUMBER CARD"
        in upper
    ):

        signals.append(
            "PERMANENT_ACCOUNT_NUMBER_CARD"
        )

    if "GOVT OF INDIA" in upper:

        signals.append(
            "GOVT_OF_INDIA"
        )

    if "GOVERNMENT OF INDIA" in upper:

        signals.append(
            "GOVERNMENT_OF_INDIA"
        )

    if "DATE OF BIRTH" in upper:

        signals.append(
            "DATE_OF_BIRTH"
        )

    if "FATHER'S NAME" in upper:

        signals.append(
            "FATHER_NAME"
        )

    return signals


# ============================================================
# MAIN EXTRACTION
# ============================================================

def extract_pan(
    ocr_result
):

    lines = get_lines(
        ocr_result
    )

    raw_text = ocr_result.get(
        "raw_text",
        ""
    )

    combined_text = "\n".join(
        item["text"]
        for item in lines
    )

    # --------------------------------------------------------
    # Extract fields
    # --------------------------------------------------------

    pan_number = extract_pan_number(
        combined_text
    )

    dob = extract_dob(
        combined_text
    )

    name = extract_name(
        lines
    )

    father_name = extract_father_name(
        lines
    )

    signals = get_signals(
        combined_text
    )

    # --------------------------------------------------------
    # Confidence
    # --------------------------------------------------------

    confidence = 0

    if (
        "INCOME_TAX_DEPARTMENT"
        in signals
    ):

        confidence += 25

    if (
        "PERMANENT_ACCOUNT_NUMBER_CARD"
        in signals
    ):

        confidence += 25

    if pan_number:

        confidence += 25

    if name:

        confidence += 10

    if father_name:

        confidence += 10

    if dob:

        confidence += 5

    confidence = min(
        confidence,
        100
    )

    # --------------------------------------------------------
    # Result
    # --------------------------------------------------------

    return {

        "success": True,

        "document_type": "PAN_CARD",

        "confidence": confidence,

        "data": {

            "pan_number":
                pan_number,

            "name":
                name,

            "father_name":
                father_name,

            "date_of_birth":
                dob,

        },

        "signals":
            signals,

    }


# ============================================================
# CLI
# ============================================================

def main():

    if len(sys.argv) != 2:

        print(
            "Usage:"
        )

        print(
            "python app/extraction/pan_extractor.py "
            "<ocr_result.json>"
        )

        sys.exit(1)

    ocr_path = Path(
        sys.argv[1]
    )

    if not ocr_path.exists():

        print(
            f"ERROR: OCR file not found: {ocr_path}"
        )

        sys.exit(1)

    try:

        with ocr_path.open(
            "r",
            encoding="utf-8"
        ) as file:

            ocr_result = json.load(
                file
            )

        result = extract_pan(
            ocr_result
        )

        output_path = (
            ocr_path.parent /
            "pan_extracted_data.json"
        )

        with output_path.open(
            "w",
            encoding="utf-8"
        ) as file:

            json.dump(
                result,
                file,
                indent=2,
                ensure_ascii=False
            )

        print(
            json.dumps(
                result,
                indent=2,
                ensure_ascii=False
            )
        )

        print()

        print(
            f"Output saved to: {output_path}"
        )

    except Exception as error:

        print(
            f"ERROR: {error}"
        )

        sys.exit(1)


if __name__ == "__main__":

    main()